set(_CATKIN_CURRENT_PACKAGE "sonar_reading")
set(sonar_reading_MAINTAINER "pi <pi@todo.todo>")
set(sonar_reading_DEPRECATED "")
set(sonar_reading_VERSION "0.0.0")
set(sonar_reading_BUILD_DEPENDS "roscpp" "std_msgs")
set(sonar_reading_RUN_DEPENDS "roscpp" "std_msgs")
set(sonar_reading_BUILDTOOL_DEPENDS "catkin")